### ISSUE TITLE
Wrong crop default option

### ISSUE THREAD

**Issue by harastaivan** [AckeeCZ/resizin-js#50]
According to [docs](https://github.com/AckeeCZ/resizin-js/blob/master/docs/Modifiers.md#crop), `crop: 'fit'` should be the default option, but as I tested it is not.

Example:
- default: https://img.resizin.com/flashsport-development/image/s_64/data/topics/russia-w-d338a3c4-sm/7017fd02e34ab5ceb3b4ef69b14314662031f141
- fill: https://img.resizin.com/flashsport-development/image/s_64-c_fill/data/topics/russia-w-d338a3c4-sm/7017fd02e34ab5ceb3b4ef69b14314662031f141
- fit: https://img.resizin.com/flashsport-development/image/s_64-c_fit/data/topics/russia-w-d338a3c4-sm/7017fd02e34ab5ceb3b4ef69b14314662031f141

Default option seems to be `fill`, but I'm not sure with that.

**Comment by horaklukas** [comment]
`fit` is truly the default option, but:

* if you use `square` modifier, crop is automatically set to `fill`
* if you use `gravity` and its value is not equal to `center`, crop is also set to `fill`

@harastaivan did you meet one of the mentioned conditions?

**Comment by horaklukas** [comment]
Fixed default value description in 739bfbc58d146e655847f4fe8f6788db4bc690ff
